# Generated by Django 3.2.9 on 2021-12-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('Mobile', models.CharField(max_length=250)),
                ('Gender', models.CharField(max_length=250)),
                ('City', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
            ],
        ),
    ]
